
# Lesser Zone
LesserZoneWeather:
  Clearly:
    BlendWeight: 60.0
    WeatherDurationMin: 1100.0
    WeatherDurationMax: 1500.0
    MaximumRepeatAmount: 2
    MaximumCooldownWeatherAmount: 1
  Cloudy:
    BlendWeight: 15.0
    WeatherDurationMin: 500.0
    WeatherDurationMax: 700.0
    MaximumRepeatAmount: 2
    MaximumCooldownWeatherAmount: 1
  Stormy:
    BlendWeight: 5.0
    WeatherDurationMin: 150.0
    WeatherDurationMax: 300.0
    MaximumRepeatAmount: 2
    MaximumCooldownWeatherAmount: 1
  LightRainy:
    BlendWeight: 15.0
    WeatherDurationMin: 500.0
    WeatherDurationMax: 700.0
    MaximumRepeatAmount: 1
    MaximumCooldownWeatherAmount: 1
  Rainy:
    BlendWeight: 5.0
    WeatherDurationMin: 500.0
    WeatherDurationMax: 700.0
    MaximumRepeatAmount: 2
    MaximumCooldownWeatherAmount: 1

# Garbage
GarbageWeather:
  Clearly:
    BlendWeight: 45.0
    WeatherDurationMin: 1000.0
    WeatherDurationMax: 1300.0
    MaximumRepeatAmount: 2
    MaximumCooldownWeatherAmount: 1
  Cloudy:
    BlendWeight: 15.0
    WeatherDurationMin: 500.0
    WeatherDurationMax: 700.0
    MaximumRepeatAmount: 2
    MaximumCooldownWeatherAmount: 1
  Stormy:
    BlendWeight: 10.0
    WeatherDurationMin: 200.0
    WeatherDurationMax: 400.0
    MaximumRepeatAmount: 2
    MaximumCooldownWeatherAmount: 1
  LightRainy:
    BlendWeight: 15.0
    WeatherDurationMin: 500.0
    WeatherDurationMax: 700.0
    MaximumRepeatAmount: 1
    MaximumCooldownWeatherAmount: 1
  Rainy:
    BlendWeight: 15.0
    WeatherDurationMin: 500.0
    WeatherDurationMax: 700.0
    MaximumRepeatAmount: 2
    MaximumCooldownWeatherAmount: 1

# Wild Island
Region_WildIsland:
  Clearly:
    BlendWeight: 30.0
    WeatherDurationMin: 1000.0
    WeatherDurationMax: 1300.0
    MaximumRepeatAmount: 2
    MaximumCooldownWeatherAmount: 1
  Cloudy:
    BlendWeight: 25.0
    WeatherDurationMin: 500.0
    WeatherDurationMax: 700.0
    MaximumRepeatAmount: 2
    MaximumCooldownWeatherAmount: 1
  Stormy:
    BlendWeight: 10.0
    WeatherDurationMin: 200.0
    WeatherDurationMax: 400.0
    MaximumRepeatAmount: 1
    MaximumCooldownWeatherAmount: 1
  LightRainy:
    BlendWeight: 20.0
    WeatherDurationMin: 500.0
    WeatherDurationMax: 700.0
    MaximumRepeatAmount: 1
    MaximumCooldownWeatherAmount: 1
  Rainy:
    BlendWeight: 15.0
    WeatherDurationMin: 500.0
    WeatherDurationMax: 700.0
    MaximumRepeatAmount: 2
    MaximumCooldownWeatherAmount: 1

# Cordon
KordonWeatherSelection:
  Clearly:
    BlendWeight: 50.0
    WeatherDurationMin: 1000.0
    WeatherDurationMax: 1300.0
    MaximumRepeatAmount: 2
  Cloudy:
    BlendWeight: 15.0
    WeatherDurationMin: 500.0
    WeatherDurationMax: 700.0
    MaximumRepeatAmount: 2
  Stormy:
    BlendWeight: 5.0
    WeatherDurationMin: 200.0
    WeatherDurationMax: 400.0
    MaximumRepeatAmount: 2
  LightRainy:
    BlendWeight: 20.0
    WeatherDurationMin: 600.0
    WeatherDurationMax: 1200.0
    MaximumRepeatAmount: 1
  Rainy:
    BlendWeight: 10.0
    WeatherDurationMin: 500.0
    WeatherDurationMax: 700.0
    MaximumRepeatAmount: 2

# Zaton
BackwaterWeatherSelection:
  Clearly:
    BlendWeight: 50.0
    WeatherDurationMin: 1000.0
    WeatherDurationMax: 1300.0
    MaximumRepeatAmount: 2
    MaximumCooldownWeatherAmount: 1
  Cloudy:
    BlendWeight: 15.0
    WeatherDurationMin: 500.0
    WeatherDurationMax: 700.0
    MaximumRepeatAmount: 2
    MaximumCooldownWeatherAmount: 1
  Stormy:
    BlendWeight: 5.0
    WeatherDurationMin: 200.0
    WeatherDurationMax: 400.0
    MaximumRepeatAmount: 2
    MaximumCooldownWeatherAmount: 1
  LightRainy:
    BlendWeight: 20.0
    WeatherDurationMin: 500.0
    WeatherDurationMax: 700.0
    MaximumRepeatAmount: 1
    MaximumCooldownWeatherAmount: 1
  Rainy:
    BlendWeight: 10.0
    WeatherDurationMin: 500.0
    WeatherDurationMax: 700.0
    MaximumRepeatAmount: 2
    MaximumCooldownWeatherAmount: 1

# Swamps
SwampWeatherSelection:
  Clearly:
    BlendWeight: 40.0
    WeatherDurationMin: 1000.0
    WeatherDurationMax: 1300.0
    MaximumRepeatAmount: 2
  Cloudy:
    BlendWeight: 10.0
    WeatherDurationMin: 500.0
    WeatherDurationMax: 700.0
    MaximumRepeatAmount: 2
  Stormy:
    BlendWeight: 5.0
    WeatherDurationMin: 200.0
    WeatherDurationMax: 400.0
    MaximumRepeatAmount: 2
  LightRainy:
    BlendWeight: 20.0
    WeatherDurationMin: 500.0
    WeatherDurationMax: 700.0
    MaximumRepeatAmount: 1
  Rainy:
    BlendWeight: 25.0
    WeatherDurationMin: 500.0
    WeatherDurationMax: 700.0
    MaximumRepeatAmount: 2

# Chemical Plant
Region_ChemicalPlant:
  Clearly:
    BlendWeight: 40.0
    WeatherDurationMin: 1000.0
    WeatherDurationMax: 1300.0
    MaximumRepeatAmount: 2
    MaximumCooldownWeatherAmount: 1
  Cloudy:
    BlendWeight: 15.0
    WeatherDurationMin: 500.0
    WeatherDurationMax: 700.0
    MaximumRepeatAmount: 2
    MaximumCooldownWeatherAmount: 1
  Stormy:
    BlendWeight: 5.0
    WeatherDurationMin: 200.0
    WeatherDurationMax: 400.0
    MaximumRepeatAmount: 2
    MaximumCooldownWeatherAmount: 1
  Rainy:
    BlendWeight: 25.0
    WeatherDurationMin: 500.0
    WeatherDurationMax: 700.0
    MaximumRepeatAmount: 2
    MaximumCooldownWeatherAmount: 1

# Rostok
RostokWeatherSelection:
  Clearly:
    BlendWeight: 60.0
    WeatherDurationMin: 1000.0
    WeatherDurationMax: 1300.0
    MaximumRepeatAmount: 2
  Cloudy:
    BlendWeight: 10.0
    WeatherDurationMin: 500.0
    WeatherDurationMax: 700.0
    MaximumRepeatAmount: 2
  Stormy:
    BlendWeight: 5.0
    WeatherDurationMin: 200.0
    WeatherDurationMax: 400.0
    MaximumRepeatAmount: 2
  LightRainy:
    BlendWeight: 15.0
    WeatherDurationMin: 600.0
    WeatherDurationMax: 1200.0
    MaximumRepeatAmount: 1
  Rainy:
    BlendWeight: 10.0
    WeatherDurationMin: 500.0
    WeatherDurationMax: 700.0
    MaximumRepeatAmount: 2

# Burnt Forest
BurnForestRegionWeather:
  Clearly:
    BlendWeight: 15.0
    WeatherDurationMin: 1000.0
    WeatherDurationMax: 1300.0
    MaximumRepeatAmount: 1
    MaximumCooldownWeatherAmount: 1
  Cloudy:
    BlendWeight: 15.0
    WeatherDurationMin: 500.0
    WeatherDurationMax: 700.0
    MaximumRepeatAmount: 1
    MaximumCooldownWeatherAmount: 1
  Stormy:
    BlendWeight: 5.0
    WeatherDurationMin: 200.0
    WeatherDurationMax: 400.0
    MaximumRepeatAmount: 2
    MaximumCooldownWeatherAmount: 1
  Rainy:
    BlendWeight: 35.0
    WeatherDurationMin: 500.0
    WeatherDurationMax: 700.0
    MaximumRepeatAmount: 2
    MaximumCooldownWeatherAmount: 1

# Duga
DugaRegionWeather:
  Clearly:
    BlendWeight: 30.0
    WeatherDurationMin: 1000.0
    WeatherDurationMax: 1300.0
    MaximumRepeatAmount: 2
    MaximumCooldownWeatherAmount: 1
  Cloudy:
    BlendWeight: 15.0
    WeatherDurationMin: 500.0
    WeatherDurationMax: 700.0
    MaximumRepeatAmount: 2
    MaximumCooldownWeatherAmount: 1
  Stormy:
    BlendWeight: 10.0
    WeatherDurationMin: 200.0
    WeatherDurationMax: 400.0
    MaximumRepeatAmount: 2
    MaximumCooldownWeatherAmount: 1
  LightRainy:
    BlendWeight: 20.0
    WeatherDurationMin: 500.0
    WeatherDurationMax: 700.0
    MaximumRepeatAmount: 1
    MaximumCooldownWeatherAmount: 1
  Rainy:
    BlendWeight: 25.0
    WeatherDurationMin: 500.0
    WeatherDurationMax: 700.0
    MaximumRepeatAmount: 2
    MaximumCooldownWeatherAmount: 1

# Malachite
MalahitWeatherSelection:
  Clearly:
    BlendWeight: 30.0
    WeatherDurationMin: 1000.0
    WeatherDurationMax: 1300.0
    MaximumRepeatAmount: 2
  Cloudy:
    BlendWeight: 10.0
    WeatherDurationMin: 500.0
    WeatherDurationMax: 700.0
    MaximumRepeatAmount: 2
  Stormy:
    BlendWeight: 10.0
    WeatherDurationMin: 200.0
    WeatherDurationMax: 400.0
    MaximumRepeatAmount: 2
  LightRainy:
    BlendWeight: 30.0
    WeatherDurationMin: 600.0
    WeatherDurationMax: 1200.0
    MaximumRepeatAmount: 1
  Rainy:
    BlendWeight: 20.0
    WeatherDurationMin: 500.0
    WeatherDurationMax: 700.0
    MaximumRepeatAmount: 2

# Yantar
YantarWeatherSelection:
  Clearly:
    BlendWeight: 25.0
    WeatherDurationMin: 1000.0
    WeatherDurationMax: 1300.0
    MaximumRepeatAmount: 2
  Cloudy:
    BlendWeight: 25.0
    WeatherDurationMin: 500.0
    WeatherDurationMax: 700.0
    MaximumRepeatAmount: 2
  Stormy:
    BlendWeight: 5.0
    WeatherDurationMin: 200.0
    WeatherDurationMax: 400.0
    MaximumRepeatAmount: 2
  LightRainy:
    BlendWeight: 30.0
    WeatherDurationMin: 600.0
    WeatherDurationMax: 1200.0
    MaximumRepeatAmount: 1
  Rainy:
    BlendWeight: 15.0
    WeatherDurationMin: 500.0
    WeatherDurationMax: 700.0
    MaximumRepeatAmount: 2

# Red Forest
RedForestWeatherSelectionMain:
  Clearly:
    BlendWeight: 55.0
    WeatherDurationMin: 1000.0
    WeatherDurationMax: 1300.0
    MaximumRepeatAmount: 2
  Stormy:
    BlendWeight: 10.0
    WeatherDurationMin: 200.0
    WeatherDurationMax: 400.0
    MaximumRepeatAmount: 2
  LightRainy:
    BlendWeight: 30.0
    WeatherDurationMin: 600.0
    WeatherDurationMax: 1200.0
    MaximumRepeatAmount: 1
  Rainy:
    BlendWeight: 15.0
    WeatherDurationMin: 500.0
    WeatherDurationMax: 700.0
    MaximumRepeatAmount: 2

# Red Forest
RedForestWeatherSelectionSide:
  Clearly:
    BlendWeight: 50.0
    WeatherDurationMin: 1000.0
    WeatherDurationMax: 1300.0
    MaximumRepeatAmount: 2
  Cloudy:
    BlendWeight: 20.0
    WeatherDurationMin: 500.0
    WeatherDurationMax: 700.0
    MaximumRepeatAmount: 1
  Stormy:
    BlendWeight: 5.0
    WeatherDurationMin: 200.0
    WeatherDurationMax: 400.0
    MaximumRepeatAmount: 1
  LightRainy:
    BlendWeight: 15.0
    WeatherDurationMin: 600.0
    WeatherDurationMax: 1200.0
    MaximumRepeatAmount: 1
  Rainy:
    BlendWeight: 10.0
    WeatherDurationMin: 500.0
    WeatherDurationMax: 700.0
    MaximumRepeatAmount: 1

# Yaniv
YanovWeatherSelection:
  Clearly:
    BlendWeight: 40.0
    WeatherDurationMin: 1000.0
    WeatherDurationMax: 1300.0
    MaximumRepeatAmount: 2
  Cloudy:
    BlendWeight: 25.0
    WeatherDurationMin: 500.0
    WeatherDurationMax: 700.0
    MaximumRepeatAmount: 2
  Stormy:
    BlendWeight: 5.0
    WeatherDurationMin: 300.0
    WeatherDurationMax: 600.0
    MaximumRepeatAmount: 1
  Rainy:
    BlendWeight: 15.0
    WeatherDurationMin: 500.0
    WeatherDurationMax: 700.0
    MaximumRepeatAmount: 2

# Jupiter
JupiterWeatherSelection:
  Clearly:
    BlendWeight: 20.0
    WeatherDurationMin: 1000.0
    WeatherDurationMax: 1300.0
    MaximumRepeatAmount: 2
  Cloudy:
    BlendWeight: 15.0
    WeatherDurationMin: 500.0
    WeatherDurationMax: 700.0
    MaximumRepeatAmount: 2
  Stormy:
    BlendWeight: 10.0
    WeatherDurationMin: 200.0
    WeatherDurationMax: 400.0
    MaximumRepeatAmount: 2
  LightRainy:
    BlendWeight: 30.0
    WeatherDurationMin: 600.0
    WeatherDurationMax: 1200.0
    MaximumRepeatAmount: 1
  Rainy:
    BlendWeight: 25.0
    WeatherDurationMin: 500.0
    WeatherDurationMax: 700.0
    MaximumRepeatAmount: 2

# Prypiat
Region_Prypiat:
  Clearly:
    BlendWeight: 50.0
    WeatherDurationMin: 1000.0
    WeatherDurationMax: 1300.0
    MaximumRepeatAmount: 2
    MaximumCooldownWeatherAmount: 1
  Cloudy:
    BlendWeight: 15.0
    WeatherDurationMin: 500.0
    WeatherDurationMax: 700.0
    MaximumRepeatAmount: 2
    MaximumCooldownWeatherAmount: 1
  Stormy:
    BlendWeight: 5.0
    WeatherDurationMin: 200.0
    WeatherDurationMax: 400.0
    MaximumRepeatAmount: 2
    MaximumCooldownWeatherAmount: 1
  LightRainy:
    BlendWeight: 20.0
    WeatherDurationMin: 500.0
    WeatherDurationMax: 700.0
    MaximumRepeatAmount: 1
    MaximumCooldownWeatherAmount: 1
  Rainy:
    BlendWeight: 10.0
    WeatherDurationMin: 500.0
    WeatherDurationMax: 700.0
    MaximumRepeatAmount: 2
    MaximumCooldownWeatherAmount: 1

# Cement Factory
CementPlantWeatherSelection:
  Clearly:
    BlendWeight: 40.0
    WeatherDurationMin: 1000.0
    WeatherDurationMax: 1300.0
    MaximumRepeatAmount: 2
  Cloudy:
    BlendWeight: 25.0
    WeatherDurationMin: 500.0
    WeatherDurationMax: 700.0
    MaximumRepeatAmount: 2
  Stormy:
    BlendWeight: 10.0
    WeatherDurationMin: 200.0
    WeatherDurationMax: 400.0
    MaximumRepeatAmount: 2
  LightRainy:
    BlendWeight: 15.0
    WeatherDurationMin: 600.0
    WeatherDurationMax: 1200.0
    MaximumRepeatAmount: 1
  Rainy:
    BlendWeight: 10.0
    WeatherDurationMin: 500.0
    WeatherDurationMax: 700.0
    MaximumRepeatAmount: 2

# Cooling Towers
GradirniWeatherSelection:
  Clearly:
    BlendWeight: 30.0
    WeatherDurationMin: 1000.0
    WeatherDurationMax: 1300.0
    MaximumRepeatAmount: 2
  Cloudy:
    BlendWeight: 20.0
    WeatherDurationMin: 500.0
    WeatherDurationMax: 700.0
    MaximumRepeatAmount: 2
  Stormy:
    BlendWeight: 20.0
    WeatherDurationMin: 200.0
    WeatherDurationMax: 400.0
    MaximumRepeatAmount: 2
  LightRainy:
    BlendWeight: 10.0
    WeatherDurationMin: 600.0
    WeatherDurationMax: 1200.0
    MaximumRepeatAmount: 1
  Rainy:
    BlendWeight: 20.0
    WeatherDurationMin: 500.0
    WeatherDurationMax: 700.0
    MaximumRepeatAmount: 2

# Cooling Tower Fire Whirl?
Gradirni_FireBreath_WeatherSelection:
  Clearly:
    BlendWeight: 15.0
    WeatherDurationMin: 600.0
    WeatherDurationMax: 1200.0
    MaximumRepeatAmount: 1
  Cloudy:
    BlendWeight: 60.0
    WeatherDurationMin: 600.0
    WeatherDurationMax: 1200.0
    MaximumRepeatAmount: 2
  Stormy:
    BlendWeight: 25.0
    WeatherDurationMin: 300.0
    WeatherDurationMax: 600.0
    MaximumRepeatAmount: 1


# Default weather?
Empty:
  Clearly:
    BlendWeight: 50.0
    WeatherDurationMin: 500.0
    WeatherDurationMax: 700.0
    MaximumRepeatAmount: 1
    MaximumCooldownWeatherAmount: 1
  Cloudy:
    BlendWeight: 30.0
    WeatherDurationMin: 500.0
    WeatherDurationMax: 700.0
    MaximumRepeatAmount: 1
    MaximumCooldownWeatherAmount: 1
  Stormy:
    BlendWeight: 10.0
    WeatherDurationMin: 500.0
    WeatherDurationMax: 700.0
    MaximumRepeatAmount: 1
    MaximumCooldownWeatherAmount: 1
  Rainy:
    BlendWeight: 10.0
    WeatherDurationMin: 500.0
    WeatherDurationMax: 700.0
    MaximumRepeatAmount: 1
    MaximumCooldownWeatherAmount: 1

# ??? Some story mission where emissions are blocked
SQ10_NoEmission_Weather:
  Clearly:
    BlendWeight: 30.0
    WeatherDurationMin: 600.0
    WeatherDurationMax: 1200.0
    MaximumRepeatAmount: 1
    MaximumCooldownWeatherAmount: 1
  Cloudy:
    BlendWeight: 35.0
    WeatherDurationMin: 600.0
    WeatherDurationMax: 1200.0
    MaximumRepeatAmount: 1
    MaximumCooldownWeatherAmount: 1
  Stormy:
    BlendWeight: 15.0
    WeatherDurationMin: 300.0
    WeatherDurationMax: 600.0
    MaximumRepeatAmount: 1
    MaximumCooldownWeatherAmount: 1
  Rainy:
    BlendWeight: 20.0
    WeatherDurationMin: 600.0
    WeatherDurationMax: 1200.0
    MaximumRepeatAmount: 1
    MaximumCooldownWeatherAmount: 1

# ??? "a fan-made, large, industrial map in Stalker Anomaly"?
Region_PromZone:
  Clearly:
    BlendWeight: 40.0
    WeatherDurationMin: 1000.0
    WeatherDurationMax: 1300.0
    MaximumRepeatAmount: 2
    MaximumCooldownWeatherAmount: 1
  Cloudy:
    BlendWeight: 20.0
    WeatherDurationMin: 500.0
    WeatherDurationMax: 700.0
    MaximumRepeatAmount: 2
    MaximumCooldownWeatherAmount: 1
  Stormy:
    BlendWeight: 5.0
    WeatherDurationMin: 200.0
    WeatherDurationMax: 400.0
    MaximumRepeatAmount: 2
    MaximumCooldownWeatherAmount: 1
  LightRainy:
    BlendWeight: 20.0
    WeatherDurationMin: 500.0
    WeatherDurationMax: 700.0
    MaximumRepeatAmount: 1
    MaximumCooldownWeatherAmount: 1
  Rainy:
    BlendWeight: 15.0
    WeatherDurationMin: 500.0
    WeatherDurationMax: 700.0
    MaximumRepeatAmount: 2
    MaximumCooldownWeatherAmount: 1

# ??? This could refer to the tornado area or The Ribs where vortex artifacts are found
VortexWeatherSelection:
  Clearly:
    BlendWeight: 40.0
    WeatherDurationMin: 600.0
    WeatherDurationMax: 1200.0
    MaximumRepeatAmount: 2
  Cloudy:
    BlendWeight: 60.0
    WeatherDurationMin: 600.0
    WeatherDurationMax: 1200.0
    MaximumRepeatAmount: 2
