
# This file is only for testing purposes.

YanovWeatherSelection:
  Clearly:
    BlendWeight: 35.0
  Cloudy:
    BlendWeight: 20.0
  Rainy:
    BlendWeight: 25.0

RostokWeatherSelection:
  Clearly:
    BlendWeight: 45.0
  LightRainy:
    BlendWeight: 15.0
